name: 'Check Author and Committer'
author: 'Danny Guo'
description: 'Checks the name and email for the author and committer'
inputs:
  github-token:
    description: 'GitHub token to use for API calls'
    required: true
  custom-error-message:
    description: 'Custom error message to provide additional context or information'
    required: false
  author-email-regex:
    description: 'JavaScript regex to validate the author email'
    required: false
  author-name-regex:
    description: 'JavaScript regex to validate the author name'
    required: false
  committer-email-regex:
    description: 'JavaScript regex to validate the committer email'
    required: false
  committer-name-regex:
    description: 'JavaScript regex to validate the committer name'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'user-check'
  color: 'green'
